services:
  - type: web
    name: parks-api
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: DB_HOST
        value: db.baausysiabockumsguxf.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: 1396
